version: "3.9"
services:
  scraper:
    build:
      context: .
      args:
        # ホストの UID / GID をそのままコンテナユーザーに反映させたい場合
        # .env で HOST_UID / HOST_GID を設定 (未設定なら 1000)
        APP_UID: ${HOST_UID:-1000}
        APP_GID: ${HOST_GID:-1000}
    container_name: d_anime_scraper
    volumes:
      - ./OUT:/app/OUT
    environment:
      - TZ=Asia/Tokyo
      # DEBUG=1 で raw.json / 解析ログを追加出力
      - DEBUG=${DEBUG:-0}
    # コンテナ実行ユーザー (ホストと合わせることで OUT/ の所有権問題を防ぐ)
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: "no"
